import React from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet,
  SafeAreaView, ScrollView, Share, Alert,
} from 'react-native';

function Row({ label, value }) {
  if (!value) return null;
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label.toUpperCase()}</Text>
      <Text style={styles.rowValue}>{value}</Text>
    </View>
  );
}

function BulletRow({ label, value }) {
  if (!value) return null;
  const items = value.split('|').map((s) => s.trim()).filter(Boolean);
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label.toUpperCase()}</Text>
      {items.map((item, i) => (
        <View key={i} style={styles.bulletItem}>
          <Text style={styles.bullet}>›</Text>
          <Text style={styles.bulletText}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

export default function ArtifactScreen({ route, navigation }) {
  const { card } = route.params;

  async function handleShare() {
    const text = [
      `# ${card.title}`,
      card.tagline,
      '',
      `PROBLEM\n${card.problem}`,
      '',
      `SOLUTION\n${card.solution}`,
      '',
      `TARGET USER\n${card.target_user}`,
      '',
      `MVP SCOPE\n${card.scope?.split('|').map(s => '• ' + s.trim()).join('\n')}`,
      '',
      `CONSTRAINTS\n${card.constraints?.split('|').map(s => '• ' + s.trim()).join('\n')}`,
      '',
      `NEXT STEP\n${card.next_step}`,
    ].join('\n');

    try {
      await Share.share({ message: text, title: card.title });
    } catch (e) {
      Alert.alert('Could not share', e.message);
    }
  }

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.scroll}>
        {/* Header card */}
        <View style={styles.heroCard}>
          <Text style={styles.heroTitle}>{card.title}</Text>
          <Text style={styles.heroTagline}>{card.tagline}</Text>
        </View>

        {/* Detail rows */}
        <View style={styles.detailCard}>
          <Row label="Problem" value={card.problem} />
          <Row label="Solution" value={card.solution} />
          <Row label="Target user" value={card.target_user} />
          <BulletRow label="MVP scope" value={card.scope} />
          <BulletRow label="Constraints" value={card.constraints} />
          <Row label="Next step" value={card.next_step} />
        </View>

        {/* Actions */}
        <TouchableOpacity style={styles.shareBtn} onPress={handleShare}>
          <Text style={styles.shareBtnText}>↑ Share Idea Card</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.newBtn}
          onPress={() => navigation.navigate('Capture')}
        >
          <Text style={styles.newBtnText}>+ New Idea</Text>
        </TouchableOpacity>

        <Text style={styles.footer}>
          Generated by NOKTA Track A · Google Gemini
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F5F5F5' },
  scroll: { padding: 20, paddingBottom: 48 },

  heroCard: {
    backgroundColor: '#111111',
    borderRadius: 12, padding: 24, marginBottom: 16,
  },
  heroTitle: {
    fontSize: 26, fontWeight: '800', color: '#FFFFFF',
    letterSpacing: -0.5, marginBottom: 8,
  },
  heroTagline: { fontSize: 15, color: '#AAAAAA', lineHeight: 22 },

  detailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12, padding: 20, marginBottom: 16,
    borderWidth: 1, borderColor: '#EEEEEE',
  },
  row: { marginBottom: 18 },
  rowLabel: {
    fontSize: 10, fontWeight: '700', letterSpacing: 1.5,
    color: '#999999', marginBottom: 6,
  },
  rowValue: { fontSize: 14, color: '#222222', lineHeight: 22 },

  bulletItem: { flexDirection: 'row', marginBottom: 4 },
  bullet: { fontSize: 16, color: '#555555', marginRight: 8, lineHeight: 22 },
  bulletText: { flex: 1, fontSize: 14, color: '#222222', lineHeight: 22 },

  shareBtn: {
    backgroundColor: '#111111',
    borderRadius: 10, paddingVertical: 15,
    alignItems: 'center', marginBottom: 10,
  },
  shareBtnText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },

  newBtn: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10, paddingVertical: 15,
    alignItems: 'center', marginBottom: 16,
    borderWidth: 1, borderColor: '#DDDDDD',
  },
  newBtnText: { color: '#111111', fontSize: 15, fontWeight: '600' },

  footer: { textAlign: 'center', color: '#AAAAAA', fontSize: 12 },
});
